### ISSUE TITLE
problem with 'scaler.sav'

### ISSUE THREAD

**Issue by snewmanSema4** [laganalab/MM-PSN#1]
Problem getting the toy eample to run:

>>> filename = 'scaler.sav'
>>> sc = joblib.load(filename)
>>> sel_exp_scaled = sc.transform(sel_exp)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/XXX/Library/Python/3.7/lib/python/site-packages/sklearn/preprocessing/_data.py", line 794, in transform
    force_all_finite='allow-nan')
  File "/Users/XXX/Library/Python/3.7/lib/python/site-packages/sklearn/base.py", line 436, in _validate_data
    self._check_n_features(X, reset=reset)
  File "/Users/XXX/Library/Python/3.7/lib/python/site-packages/sklearn/base.py", line 373, in _check_n_features
    "The reset parameter is False but there is no "
RuntimeError: The reset parameter is False but there is no n_features_in_ attribute. Is this estimator fitted?

**Comment by snewmanSema4** [comment]
Installed sklearn 0.22.2.post1 and got a bit further.
But now, XGBoost is complaining:
  If you are loading a serialized model (like pickle in Python) generated by older
  XGBoost, please export the model by calling `Booster.save_model` from that version
  first, then load it back in current version.  There's a simple script for helping
  the process ...
What version of XGBoost do I need?
